spring.application.name=CriptoAnaliser
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cripto
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

cripto.alerta.lucro-minimo-pct=0.30
cripto.dados.idade-maxima-segundos=120